### ISSUE TITLE
Make map and source list more noticeable 

### ISSUE THREAD

**Issue by ybce** [aliyasser20/News-App#3]
## Map: 

![image](https://user-images.githubusercontent.com/16041846/73144238-ae6bbd80-4071-11ea-9ae4-c87077d92d91.png)

## Sources List: 

![image](https://user-images.githubusercontent.com/16041846/73144244-bb88ac80-4071-11ea-8431-761dc9618af2.png)

Would be nice if there is more indication that these are clickable elements, maybe be a downwards facing arrow.

**Comment by aliyasser20** [comment]
This issue has been fixed
